[project]
name = "xiaozhi-mcp"
version = "0.1.0"
description = "xiaozhi-mcp project"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [{ name = "Your Name" }]

dependencies = [
    "o365>=2.0.26",
    "aiohttp",
    "aiohttp>=3.9.0",
    "bring-api>=1.1.0",
    "fastmcp>=2.13.0.2",
    "google-api-python-client>=2.100.0",
    "google-auth-httplib2>=0.1.0",
    "google-auth-oauthlib>=1.0.0",
    "httpx>=0.27.0",
    "mcp-proxy>=0.10.0",
    "mcp>=1.23.0",
    "pydantic>=2.12.3",
    "pyrogram>=2.0.0",
    "python-dotenv>=1.2.1",
    "tavily-python>=0.3.0",
    "tgcrypto>=1.2.0",
    "websockets>=15.0.1",
    "httpx",
    "curl-cffi>=0.15.0",
    "youtube-transcript-api>=1.2.4",
]

[project.scripts]
xiaozhi-mcp = "xiaozhi_mcp.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "pytest-asyncio>=0.23.0",
    "ruff",
    "mypy"
]
# uv will read PEP 621 metadata

[tool.mypy]
disallow_untyped_defs = true
exclude = ['migrations', 'lambda_pymupdf', 'dcf_testing']
ignore_missing_imports = true

python_version = '3.11'
show_error_codes = true
warn_unused_configs = true

[tool.ruff]
exclude = ['.venv', 'migrations']
indent-width = 4
line-length = 121
target-version = 'py311'

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
ignore = [
    'ANN002',
    'ANN003',
    'D102',
    'D103',
    'BLE001',
    'ANN001',
    'ANN201',
    'D101',
    'T201',
    'E501',
    'E731',
    'FBT002', # maybe we doesn't need this linter
    # turn back after add all docstrings
    'PLR0915', # turn on to find complex structures
    'PLR0912', # turn on to find complex structures
    'RUF027', # unblock after finish promt management
    'SIM117',
    'D401',
    'ANN401',
    'ASYNC230',
    'B008',
    'B904',
    'B904',
    'COM812',
    'COM819',
    'D203',
    'D203',
    'D212',
    'D212',
    'EM',
    'EM',
    'EXE002',
    'EXE002',
    'FBT001',
    'FBT003',
    'FBT003',
    'ISC001',
    'N805',
    'N805',
    'N818',
    'N818',
    'PLR0913',
    'PLR0913',
    'PLR0914',
    'PLR0917',
    'PLR0917',
    'PLR1702',
    'PLR2004',
    'PLR2004',
    'PLR6301',
    'PLR6301',
    'PLW0603',
    'PLW1508',
    'PLW1508',
    'PLW1508',
    'PLW2901',
    'PLW2901',
    'RET506',
    'RUF001',
    'RUF001',
    'RUF002',
    'RUF003',
    'RUF006',
    'RUF029',
    'RUF052',
    'RUF052',
    'TD002',
    'TD003',
    'TRY',
    'TRY',
    'UP040'
]
preview = true
select = [
    'A', # flake8-builtins
    'ANN', # flake8-annotations
    'ASYNC', # flake8-async
    'B', # flake8-bugbear
    'BLE', # flake8-blind-except
    'C4', # flake8-comprehensions
    'COM', # flake8-commas
    'D', # pydocstyle
    'E', # pycodestyle
    'F', # Pyflakes
    'FBT', # flake8-boolean-trap
    'I', # isort
    'ICN', # flake8-import-conventions
    'INP', # flake8-no-pep420
    'ISC', # flake8-implicit-str-concat
    'N', # pep8-naming
    'PIE', # flake8-pie
    'PL', # pylint
    'PT', # flake8-pytest-style
    'Q', # quotes
    'RET', # flake8-return
    'RSE', # flake8-raise
    'RUF', # Ruff-specific rules
    'S', # flake8-bandit
    'SIM', # flake8-simplify
    'SLOT', # flake8-slots
    'T20', # print search
    'TD', # flake8-todos
    'UP', # pyupgrade
    'W', # warning
    'YTT'  # flake8-2020
]
per-file-ignores = { 'tests/*' = ['S101'] }

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.pytest.ini_options]
filterwarnings = [
    'ignore::DeprecationWarning', # Ignores all DeprecationWarnings
    'ignore:.*U.*mode is deprecated:DeprecationWarning', # Ignores specific DeprecationWarnings matching a regex
    'error', # Transforms all other warnings into errors
    'ignore::UserWarning', # Ignores all UserWarnings
]
